@AutonomousCars.Api_HostAddress = http://localhost:5191

GET {{AutonomousCars.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AutonomousCars.Api_HostAddress}}/token/map
Accept: application/json

###

POST({{AutonomousCars.Api_HostAddress}}/

### 
