name: Run Azure Login with OIDC
on:
  workflow_run:
    workflows: [continuous]
    types:
      - completed
    branches:
      - 'main'
  schedule:
    - cron: '0 7 * * *'

env:
  AZURE_WEBAPP_NAME: app-autonomouscarsec2e9966
  AZURE_WEBAPP_PACKAGE_PATH: './artifacts/api'
  AZURE_STATIC_WEBAPP_PACKAGE_PATH: './build'
  
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: 'Deploy web app'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: 'Deploy static app'
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          package: ${{ env.AZURE_STATIC_WEBAPP_PACKAGE_PATH }}
      
          
          