name: Run Azure Login with OIDC
on:
  push:
    branches:
      - 'feature/set-up-CD' # TODO only for test, need to be erased 
  workflow_run:
    workflows: [continuous]
    types:
      - completed
    branches:
      - 'main'
  schedule:
    - cron: '0 7 * * *'

env:
  AZURE_WEBAPP_NAME: app-autonomouscarsec2e9966
  AZURE_WEBAPP_PACKAGE_PATH: './artifacts/api'
  AZURE_STATIC_WEBAPP_PACKAGE_PATH: './build'
  
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'test secret' # test to have secret value
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "$SUPER_SECRET"
      - name: 'Checkout repo'
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: 'Deploy web app'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: 'Deploy static app'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          package: ${{ env.AZURE_STATIC_WEBAPP_PACKAGE_PATH }}
      
          
          
