name: Run deployment with OIDC
on:
  workflow_run:
    workflows: [continuous]
    types:
      - completed
    branches:
      - 'main'
  schedule:
    - cron: '0 7 * * *'

env:
  AZURE_WEBAPP_NAME:  ${{ vars.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: './api'
  AZURE_STATIC_WEBAPP_APP_LOCATION: '.'

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Download back-end artifact'
        id: download-back-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: continuous.yml
          workflow_conclusion: completed
          name: backend
      - name: 'Deploy web app'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: 'Download front-end artifact'
        id: download-front-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: front-ci.yml
          workflow_conclusion: completed
          name: artifact
      - name: 'Deploy static app'
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: ${{ env.AZURE_STATIC_WEBAPP_APP_LOCATION }}
          skip_app_build: true
          output_location: ''
          action: 'upload'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      
          
          
