name: Run Azure Login with OIDC
on:
  push:
    branches:
      - 'feature/set-up-CD' # TODO only for test, need to be erased 
  workflow_run:
    workflows: [continuous]
    types:
      - completed
    branches:
      - 'main'
  schedule:
    - cron: '0 7 * * *'

env:
  AZURE_WEBAPP_NAME: app-autonomouscarsec2e9966
  AZURE_WEBAPP_PACKAGE_PATH: './artifacts/api'
  AZURE_STATIC_WEBAPP_PACKAGE_PATH: './build'
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 76e7ba0e-8690-4ec1-9fb5-d71132263856
          tenant-id: d0cf1ed1-5a50-4a79-8afb-e642a3308fd1
          subscription-id: be04e777-42ad-46b3-b592-efc468e08696
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: 'Deploy web app'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: 'Deploy static app'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          package: ${{ env.AZURE_STATIC_WEBAPP_PACKAGE_PATH }}
      
          
          
