name: Frontend CI Pipeline 

on: 
  push: 
    branches: 
      - front_ci_artifact
    #paths: 
    #   - src/front/**
  pull_request: 
    branches:
      - main
    paths: 
      - src/front/**

defaults:
  run:
    working-directory: ./src/front

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with: 
          version: 8.9.0
        
      - name: Install dependencies 
        run: pnpm install
      
      - name: Build Application
        run: pnpm build

      - name: Check typing with Typescript
        run: pnpm type-check

      - name: Run Tests
        run: pnpm test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./src/front/.output #Build folder created by Nuxt