name: Frontend CI Pipeline 

on: 
  push: 
    branches: 
      - front_ci
    pull-request: 
      branches:
        - main
  
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: pnpm/setup-pnpm@v2
        with: 
          version: 8.9.0
        
      - name: Install dependencies 
        working-directory: ./src/front
        run: pnpm install
      
      - name: Build Application
        working-directory: ./src/front
        run: pnpm run build

      - name: Check typing with Typescript
        working-directory: ./src/front
        run: pnpm run type-check

      - name: Run Tests
        working-directory: ./src/front
        run: pnpm run test




